const GET_WEATHER_FOR_CITY = 'GET_WEATHER_FOR_CITY';

const GET_WEATHER_FOR_CITIES = 'GET_WEATHER_FOR_CITIES';
const SET_WEATHER_FOR_CITIES = 'SET_WEATHER_FOR_CITIES';

const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const ActionTypes = {
  GET_WEATHER_FOR_CITY,
  GET_WEATHER_FOR_CITIES,
  SET_WEATHER_FOR_CITIES,
  SET_ERROR_MESSAGE,
};
